import { jsPDF } from "jspdf";

export type PdfPayload = {
  diseaseName: string;
  severity: string;
  confidence: number;
  rx: string;
  createdAt?: string;
  imageUrl?: string; // data URL or http(s) URL
};

async function urlToDataUrl(url: string): Promise<string | null> {
  try {
    if (url.startsWith("data:")) return url;
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise<string>((resolve, reject) => {
      const fr = new FileReader();
      fr.onload = () => resolve(fr.result as string);
      fr.onerror = reject;
      fr.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function exportDiagnosisPdf(p: PdfPayload) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = M;

  // Header band
  doc.setFillColor(107, 142, 35);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("LeafRx — Diagnosis Report", M, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("AI-Powered Plant Disease Detection", M, 60);
  y = 100;

  // Image
  if (p.imageUrl) {
    const dataUrl = await urlToDataUrl(p.imageUrl);
    if (dataUrl) {
      try {
        const imgW = 200;
        const imgH = 200;
        doc.addImage(dataUrl, "JPEG", W - M - imgW, y, imgW, imgH, undefined, "FAST");
      } catch {
        // ignore image errors
      }
    }
  }

  // Disease name
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  const nameLines = doc.splitTextToSize(p.diseaseName, W - 2 * M - 220);
  doc.text(nameLines, M, y + 14);
  y += 14 + nameLines.length * 22;

  // Meta line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(90, 90, 90);
  const date = p.createdAt ? new Date(p.createdAt).toLocaleString() : new Date().toLocaleString();
  doc.text(`Date: ${date}`, M, y);
  y += 18;

  // Severity badge
  const sevColors: Record<string, [number, number, number]> = {
    Severe: [239, 83, 80], High: [255, 112, 67], Moderate: [255, 167, 38], Low: [102, 187, 106],
  };
  const c = sevColors[p.severity] || [120, 120, 120];
  doc.setFillColor(c[0], c[1], c[2]);
  doc.roundedRect(M, y, 90, 22, 6, 6, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(p.severity, M + 45, y + 15, { align: "center" });

  // Confidence
  doc.setTextColor(40, 40, 40);
  doc.setFont("helvetica", "normal");
  doc.text(`Confidence: ${p.confidence}%`, M + 110, y + 15);
  y += 44;

  // Confidence bar
  const barW = W - 2 * M;
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(M, y, barW, 10, 5, 5, "F");
  doc.setFillColor(107, 142, 35);
  doc.roundedRect(M, y, (barW * p.confidence) / 100, 10, 5, 5, "F");
  y += 30;

  // Rx box
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(107, 142, 35);
  doc.text("PRESCRIBED TREATMENT (Rx)", M, y);
  y += 14;

  doc.setDrawColor(107, 142, 35);
  doc.setLineWidth(0.5);
  doc.setFillColor(248, 250, 245);
  const rxLines = doc.splitTextToSize(p.rx, W - 2 * M - 24);
  const rxBoxH = rxLines.length * 16 + 24;
  doc.roundedRect(M, y, W - 2 * M, rxBoxH, 8, 8, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text(rxLines, M + 12, y + 18);
  y += rxBoxH + 24;

  // Disclaimer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  const disc = doc.splitTextToSize(
    "This report is generated by LeafRx AI for informational purposes only. " +
      "Consult a local agronomist before applying chemical treatments. " +
      "Follow product labels and safety guidelines.",
    W - 2 * M,
  );
  doc.text(disc, M, y);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("LeafRx · leafrx.app", M, doc.internal.pageSize.getHeight() - 24);
  doc.text(
    `Generated ${new Date().toLocaleString()}`,
    W - M,
    doc.internal.pageSize.getHeight() - 24,
    { align: "right" },
  );

  const safeName = p.diseaseName.replace(/[^a-z0-9]+/gi, "_").slice(0, 40);
  doc.save(`LeafRx_${safeName}_${Date.now()}.pdf`);
}
